version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: catalogo-rabbitmq
    ports:
      - "5672:5672"    # Porta do RabbitMQ
      - "15672:15672"  # Porta do Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - catalogo-network

volumes:
  rabbitmq-data:

networks:
  catalogo-network:
    driver: bridge